FROM golang:1.24.1-alpine AS builder
WORKDIR /app
COPY . .
RUN apk add --no-cache git
RUN go mod download
RUN go build -o app ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .
RUN touch .env          # tạo file .env rỗng
EXPOSE 8080
CMD ["./app"]
